name: Integration Test WF
on: 
  push:
    branches:
      - master
  pull_request:
    types: [ labeled ]
    branches:
      - master
env:
  KIND_URL: https://kind.sigs.k8s.io/dl
  KIND_VER: v0.8.1
  KIND_ENV: kind-linux-amd64

jobs:
  Kafka-Test:
    if: ${{ github.event.label.name == 'kafka' }} || ${{ github.event.label.name == 'KAFKA' }} || ${{ github.event.label.name == 'Kafka' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the current repo
        uses: actions/checkout@v1
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            kafkachanges:
              - 'integration/kafka/**'    
              - 'kafka-http-connector/**'
      - name: Install Kind Cluster
        if: steps.filter.outputs.kafkachanges == 'true'
        run: |
          curl -Lo ./kind $KIND_URL/$KIND_VER/$KIND_ENV      
          chmod +x ./kind
          sudo mv ./kind /usr/bin/
        env:
          KIND_URL: https://kind.sigs.k8s.io/dl
          KIND_VER: v0.8.1
          KIND_ENV: kind-linux-amd64
      - name: Install KEDA using HELM 
        if: steps.filter.outputs.kafkachanges == 'true'      
        run: |
          cd integration/
          ./registry.sh
          helm repo add kedacore https://kedacore.github.io/charts
          helm repo update
          kubectl create namespace keda
          helm install keda kedacore/keda --namespace keda
      - name: Create Docker Image for HTTP server
        if: steps.filter.outputs.kafkachanges == 'true'      
        run: |
          cd integration/server/
          docker build -t localhost:5000/http-server:latest .
          docker push localhost:5000/http-server:latest
      - name: Create Docker Image for KEDA Connector
        if: steps.filter.outputs.kafkachanges == 'true'      
        run: |
          cd kafka-http-connector/
          docker build -t localhost:5000/kafka-connector:latest .
          docker push localhost:5000/kafka-connector:latest
      - name: Create Docker Image for Consumer
        if: steps.filter.outputs.kafkachanges == 'true'      
        run: |
          cd integration/kafka/consumer/
          docker build -t localhost:5000/consumer:latest .
          docker push localhost:5000/consumer:latest
      - name: Deploy Kafka cluster
        if: steps.filter.outputs.kafkachanges == 'true'      
        run: |
          cd integration/kafka/kubernetes/
          kubectl create namespace kafka
          curl -L http://strimzi.io/install/latest | sed 's/namespace: .*/namespace: kafka/' | kubectl apply -f - -n kafka
          sleep 10s
          kubectl apply -f kafka-cluster.yaml
          echo "Kafka Cluster is getting up."
          kubectl wait -f kafka-cluster.yaml --for=condition=ready --timeout=-1s -n kafka
          sleep 2m
          kubectl get pods -n kafka
          kubectl wait pod -l app.kubernetes.io/name=zookeeper --for=condition=ready --timeout=-1s -n kafka
      - name: Create Kafka topics
        if: steps.filter.outputs.kafkachanges == 'true'      
        run: |
          cd integration/kafka/kubernetes/
          kubectl apply -f kafka-req-topic.yaml 
          kubectl apply -f kafka-err-topic.yaml
          kubectl apply -f kafka-res-topic.yaml
      - name: Bring up HTTP Server
        if: steps.filter.outputs.kafkachanges == 'true'      
        run: |
          cd integration/server/
          kubectl apply -f server.yaml -n kafka
          kubectl wait pod -l app=http --for=condition=ready --timeout=-1s -n kafka
      - name: Deploy Keda Connector and Keda ScaledObject
        if: steps.filter.outputs.kafkachanges == 'true'      
        run: |
          cd integration/kafka/kubernetes/ 
          kubectl apply -f keda-deployment.yml
          kubectl get pods -n kafka
          docker images
          sleep 15s
          kubectl get pods -n kafka
          kubectl wait pod -l keda=kafka --for=condition=ready --timeout=30s -n kafka
          kubectl apply -f Keda-ScaledObj.yml 
      - name: Produce messages Using Producer
        if: steps.filter.outputs.kafkachanges == 'true'      
        run: |
          cd integration/kafka/kubernetes/
          kubectl apply -f kafka-produer.yaml -n kafka
          kubectl wait -f kafka-produer.yaml --for=condition=complete --timeout=-1s -n kafka
          kubectl delete job pi -n kafka
      - name: Collect Consumer Messages
        if: steps.filter.outputs.kafkachanges == 'true'      
        run: |
          kubectl get pods -n kafka
          cd integration/kafka/consumer/
          kubectl apply -f consumer-deployment.yaml
          kubectl wait pod -l app=consumer --for=condition=ready --timeout=-1s -n kafka
          kubectl logs -l app=consumer --all-containers=true -n kafka
  Rabbit-Test:
    if: ${{ github.event.label.name == 'rabbitmq' }} || ${{ github.event.label.name == 'Rabbitmq' }}${{ github.event.label.name == 'RABBITMQ' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the current repo
        uses: actions/checkout@v1
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            rabbitmqchanges:
              - 'integration/rabbitmq/**'    
              - 'rabbitmq-http-connector/**'                   
      - name: Install Kind Cluster
        if: steps.filter.outputs.rabbitmqchanges == 'true'      
        run: |
          curl -Lo ./kind $KIND_URL/$KIND_VER/$KIND_ENV
          chmod +x ./kind
          sudo mv ./kind /usr/bin/
        env:
          KIND_URL: https://kind.sigs.k8s.io/dl
          KIND_VER: v0.8.1
          KIND_ENV: kind-linux-amd64
      - name: Install KEDA using HELM
        if: steps.filter.outputs.rabbitmqchanges == 'true'        
        run: |
          cd integration/
          ./registry.sh
          helm repo add kedacore https://kedacore.github.io/charts
          helm repo update
          kubectl create namespace keda
          helm install keda kedacore/keda --namespace keda
      - name: Create Docker Image for HTTP server
        if: steps.filter.outputs.rabbitmqchanges == 'true'        
        run: |
          cd integration/server/
          docker build -t localhost:5000/http-server:latest .
          docker push localhost:5000/http-server:latest
      - name: Create Docker Image for KEDA Connector
        if: steps.filter.outputs.rabbitmqchanges == 'true'        
        run: |
          cd rabbitmq-http-connector/
          docker build -t localhost:5000/rabbit-keda:latest .
          docker push localhost:5000/rabbit-keda:latest
      - name: Create Docker Image for Publisher
        if: steps.filter.outputs.rabbitmqchanges == 'true'        
        run: |
          cd integration/rabbitmq/publisher/
          docker build -t localhost:5000/rabbit-publisher:latest .
          docker push localhost:5000/rabbit-publisher:latest
      - name: Create Docker Image for Consumer
        if: steps.filter.outputs.rabbitmqchanges == 'true'        
        run: |
          cd integration/rabbitmq/consumer/
          docker build -t localhost:5000/rabbit-consumer:latest .
          docker push localhost:5000/rabbit-consumer:latest
      - name: Deploy Rabbitmq Deployment files
        if: steps.filter.outputs.rabbitmqchanges == 'true'        
        run: |
          cd integration/rabbitmq/kubernetes/
          kubectl create ns rabbits
          kubectl apply -n rabbits -f rabbit-rbac.yaml
          kubectl apply -n rabbits -f rabbit-configmap.yaml
          kubectl apply -n rabbits -f rabbit-secret.yaml
          kubectl apply -n rabbits -f rabbit-statefulset.yaml
          bash rabbitmq-cluster-instances.sh 
      - name: Bring up HTTP Server
        if: steps.filter.outputs.rabbitmqchanges == 'true'        
        run: |
          cd integration/server/
          kubectl apply -f server.yaml -n rabbits
          kubectl wait pod -l app=http --for=condition=ready --timeout=-1s -n rabbits
      - name: Publish messages in a queue
        if: steps.filter.outputs.rabbitmqchanges == 'true'        
        run: |
          cd integration/rabbitmq/publisher/
          kubectl apply -f deployment.yaml
          kubectl apply -f publisher-job.yaml
      - name: Bring up the consumer queue and Listen for incoming messages
        if: steps.filter.outputs.rabbitmqchanges == 'true'        
        run: |
          cd integration/rabbitmq/consumer/
          kubectl apply -f consumer-deployment.yaml
      - name: Deploy Keda Connector and Keda ScaledObject
        if: steps.filter.outputs.rabbitmqchanges == 'true'        
        run: |
          cd integration/rabbitmq/kubernetes/
          kubectl apply -f keda-deployment.yml
          kubectl wait pod -l keda=rabbitmq --for=condition=ready --timeout=-1s -n rabbits
          kubectl apply -f Keda-ScaledObj.yml
      - name: Get consumed messages from queue
        if: steps.filter.outputs.rabbitmqchanges == 'true'        
        run: |
          sleep 10s
          kubectl logs  -n rabbits deployment.apps/rabbitmq-consumer
  SQS-Test:
    if: ${{ github.event.label.name == 'aws_sqs' }} || ${{ github.event.label.name == 'Aws_Sqs' }}${{ github.event.label.name == 'AWS_SQS' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the current repo
        uses: actions/checkout@v1
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            sqschanges:
              - 'integration/aws_sqs/**'    
              - 'aws-sqs-http-connector/**'                   
      - name: Install Kind Cluster
        if: steps.filter.outputs.sqschanges == 'true'      
        run: |
          curl -Lo ./kind $KIND_URL/$KIND_VER/$KIND_ENV
          chmod +x ./kind
          sudo mv ./kind /usr/bin/
        env:
          KIND_URL: https://kind.sigs.k8s.io/dl
          KIND_VER: v0.8.1
          KIND_ENV: kind-linux-amd64
      - name: Install KEDA using HELM
        if: steps.filter.outputs.sqschanges == 'true'        
        run: |
          cd integration/
          ./registry.sh
          helm repo add kedacore https://kedacore.github.io/charts
          helm repo update
          kubectl create namespace keda
          helm install keda kedacore/keda --namespace keda
      - name: Create Docker Image for HTTP server
        if: steps.filter.outputs.sqschanges == 'true'        
        run: |
          cd integration/server/
          docker build -t localhost:5000/http-server:latest .
          docker push localhost:5000/http-server:latest
          kubectl apply -f server.yaml  
      - name: Create Docker Image for KEDA Connector
        if: steps.filter.outputs.sqschanges == 'true'        
        run: |
          cd aws-sqs-http-connector
          docker build -t localhost:5000/aws-sqs-connector:latest .
          docker push localhost:5000/aws-sqs-connector:latest
      - name: Create Docker image with AWS CLI in KEDA Connetor
        if: steps.filter.outputs.sqschanges == 'true'        
        run: |
          cd integration/aws_sqs/kubernetes 
          docker build -t localhost:5000/aws-sqs-test-connector:latest .
          docker push localhost:5000/aws-sqs-test-connector:latest
      - name: Deploy Keda Connector, Keda ScaledObject and Localstack
        if: steps.filter.outputs.sqschanges == 'true'        
        run: |
          cd integration/aws_sqs/kubernetes 
          kubectl apply -f keda-deployment.yml
          kubectl apply -f keda-scaledObj.yml
          kubectl apply -f localstack.yaml
      - name: Build and Deploy test queue
        if: steps.filter.outputs.sqschanges == 'true'        
        run: |       
          cd integration/aws_sqs/tests
          docker build -t localhost:5000/test-queue:latest .
          docker push localhost:5000/test-queue:latest
          kubectl apply -f test.yaml
          sleep 10s
          kubectl get pods
          kubectl wait pod -l app=queue --for=condition=ready --timeout=200s
      - name: Get consumed messages from queue
        if: steps.filter.outputs.sqschanges == 'true'        
        run: |
          sleep 10s
          kubectl logs -f -l app=queue
